# Generated by Django 5.2.17 on 2026-09-11 04:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                ("department", models.CharField(max_length=120)),
                ("location", models.CharField(max_length=200)),
                ("employment_type", models.CharField(max_length=120)),
                ("experience", models.CharField(max_length=120)),
                ("salary", models.CharField(blank=True, max_length=120, null=True)),
                ("description", models.TextField()),
                ("requirements", models.JSONField(default=list)),
                ("responsibilities", models.JSONField(default=list)),
                ("benefits", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=30)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("date_of_birth", models.DateTimeField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=50, null=True)),
                ("qualification", models.CharField(max_length=200)),
                ("university", models.CharField(blank=True, max_length=200, null=True)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("experience", models.TextField(blank=True, null=True)),
                (
                    "current_company",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "expected_salary",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                ("cover_letter", models.TextField()),
                ("skills", models.TextField(blank=True, null=True)),
                ("resume_url", models.CharField(max_length=500)),
                ("additional_documents", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Reviewing", "Reviewing"),
                            ("Shortlisted", "Shortlisted"),
                            ("Interview", "Interview"),
                            ("Selected", "Selected"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="portal.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
