services:
  - type: web
    name: rawal-engineering-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        sync: false
      - key: CLIENT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
