import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import MarketingHeader from "../components/MarketingHeader";

const projects = [{ name: "Interior and Exterior Design", type: "Exterior Design · Interior Design", image: "url('/exterior.svg')", text: "Thoughtful exterior and interior design shaped around people, place, and everyday use." }, { name: "3D Design", type: "3D Visualization", image: "url('/inter.svg')", text: "Clear three-dimensional visuals that help ideas become easy to understand before construction." }, { name: "Construction", type: "Construction Delivery", image: "url('/related.svg')", text: "Practical construction coordination that carries the design through to a durable finished result." }];

export default function ProjectsPage() {
  return <main className="min-h-screen bg-[linear-gradient(135deg,#f9e7bb,#e7c978)] text-[var(--ink)]"><MarketingHeader /><header className="px-5 pb-20 pt-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow !text-[var(--teal-dark)]">Selected work</p><h1 className="display mt-5 max-w-4xl text-6xl leading-[.94] sm:text-8xl">Made to <em>matter.</em></h1><p className="mt-8 max-w-2xl text-xl leading-8 text-[var(--ink)]/65">A selection of places and systems where careful thinking became something people can use.</p></div></header><section className="section-pad pt-0"><div className="mx-auto max-w-7xl space-y-16">{projects.map((project, index) => <article key={project.name} className={`grid gap-8 md:grid-cols-[1.25fr_.75fr] md:items-end ${index % 2 ? "md:grid-cols-[.75fr_1.25fr]" : ""}`}><div className={`project-image aspect-[4/3] overflow-hidden rounded-2xl border border-[var(--gold-strong)]/50 shadow-[0_18px_35px_rgba(121,89,33,0.14)] ${index % 2 ? "md:order-2" : "md:order-1"}`} style={{ "--image": project.image } as React.CSSProperties} /><div className={index % 2 ? "md:order-1" : "md:order-2"}><p className="text-xs uppercase tracking-[.15em] text-[var(--teal-dark)]">{project.type}</p><h2 className="display mt-3 text-4xl leading-none">{project.name}</h2><p className="mt-5 leading-7 text-[var(--ink)]/65">{project.text}</p></div></article>)}</div></section><div className="px-5 pb-20 text-center"><Link href="/contact" className="btn-dark">Discuss a project <ArrowUpRight size={17} /></Link></div></main>;
}
